baseurl: /
languageCode: en-us
title: 珠峰
theme: "hugo-ivy"
googleAnalytics: ""
disqusShortname: ""
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$"]
preserveTaxonomyNames: true
footnotereturnlinkcontents: ↩

permalinks:
  note: /note/:year/:month/:day/:slug/
  post: /post/:year/:month/:day/:slug/

menu:
  main:
    - name: "主页"
      url: "/"
      weight: 1
    - name: "关于我"
      url: "/about/"
      weight: 2
    - name: "分类"
      url: "/categories/"
      weight: 3
    - name: "标签"
      url: "/tags/"
      weight: 4
    #- name: "Subscribe"
    #  url: "/index.xml"

params:
  description: "\"经济\"是经世和济民"
  footer: "&copy; [珠峰](https://zhufeng.netlify.app/) 2024-{Year} | [Github](https://github.com/zhufeng7)"
  highlightjsLang: ["latex"]
  highlightjsTheme: "github"
  highlightjsVersion: "11.7.0"

markup:
  highlight:
    codeFences: false
  goldmark:
    renderer:
      unsafe: true
