---
title: 看盘复盘
author: 珠峰
date: '2024-03-12'
slug: 如何看盘复盘
categories:
  - 交易笔记
tags:
  - 笔记
  - 股票
---

看盘，能让自己清晰的掌握当天市场涨跌情况、资金流向情况、板块轮动情况、龙头切换和延续情况、市场情绪情况、突发事件情况、国家、国际局势情况等等，这些对于股票交易来讲是非常重要的。但盯盘就比较耗费精力，我没那么多时间，所以一般不会盯盘，操作级别也比较大。

复盘，则是对当天市场做一个总结，在看盘的基础上做一个更深入的分析，从而更加清晰地看清市场，做出更合理的操作策略。

**为什么同样的技术，选出来的股票，有的不涨，有的则成为黑马，而大部分人买到的都是不涨的呢？原因就在于纯技术选股太过单一，考虑的因素太过片面，导致纯技术不容易买到黑马。要知道，黑马是在政策支持、庄家操纵、公司自身实力很强等等综合因素下产生的，是需要内在因素推动的；而不是像表面上受到均线支撑或者突破某个压力位那样简单。**

而我们**看盘复盘，看的就是内在因素，复的就是内在逻辑**。 比如盘中某板块异动或者某个股逆势拉升，我们盘中就看到了，那我们可以在盘中，也可以在盘后去分析为什么异动？是不是有政策利好？是不是有消息刺激？是不是有人操纵？等等等等，通过综合的评估后，得出这个板块有没有机会，这个股票值不值得操作，最后才会得出具体的操作思路。

# 如何看盘

## 看盘页面制作

每个投资者都应该结合自身情况做一个适合自己的看盘页面，因为一个好的看盘页面能让自己及时关注到资金流向、板块轮动、个股异动等等重要信息，从而捕捉到比较好的操作机会。

### 主要元素

* 热点板块，把握市场资金最新流向，实时把握热点方向。

* 个股排名，实时把握强势个股情况，结合板块分析，选找机会。

* 综合排名，随时监测各种异动的个股，比如急速拉升，巨幅震荡，量比很高等异动的股票。

* 个股日线图，随时掌握各个股票日线情况，技术情况。

* 筹码分布，观察股票中的资金成本位置以及主力操作阶段。

* 个股分时，把握分时买点，观察盘面异动。

* 大盘分时，实时掌握大环境情况。

* 盘口信息，观察支撑压力、观察主力手法，熟悉股性。

* 分时成交，观察成交异动。

其实只要你用心，坚持看盘一年，你的盘感会得到质的飞跃，但是这对事件自由要求比较高，很多朋友没有这个条件，不过没关系，盘后复盘也是可以的。

## 集合竞价（短线操作方式）

**集合竞价主要找高开的强势个股**

### 基础了解

股票开盘是从集合竞价开始的，集合竞价决定了一天之中的开盘价格，所以集合竞价很重要。

竞价方式分为集合竞价和连续竞价，集合竞价是指对规定的一段时间内将所有合规的买卖申报一次性集中撮合的竞价方式。连续竞价是指在一段时间内连续不停的对接受的买卖申报进行撮合的竞价方式。

竞价原则：价格优先，时间优先。在这个基础上，集合竞价还要体现“成交量优先”，即在符合上述条件的基础上，撮合成交量最大的价格为开盘价，这点经常被主力机构所利用。因此，股价的异常集合竞价往往是庄家利用手中的筹码和资金所为， 而正常的集合竞价结果反应了整体市场的看空或看多。

### 集合竞价的看盘要点解析

9点15到9点20的集合竞价可以撤单，9点20到9点25之间的任何挂单都不可撤销，所以9点20分到9点25分的集合竞价表现比较真实。此时，如果这个阶段的价格呈逐级拉升态势，对应的量能成稳步放大，则说明市场抢筹明显，做多情绪高涨，这种形态最为健康。

在集合竞价过程中，要及时观察盘口，一个真实有效的高开集合竞价，往往它的撮合手数（即成交量能）是在不断的放大，并不是时大时小或者越来越小。另外，在9点25分统一撮合成交后，要在分笔成交中看一下撮合成交的手数（**极少成交数量的高开有效性低、量大的成交高开有效性高，其实可以看做持高开态度的人数或者资金量**），可以结合该个股的流通盘来综合判断。

* 流通盘小于一个亿，撮合成交要在300手以上
* 流通盘1-5亿，撮合成交要在500手以上
* 流通盘5-20亿，撮合成交要在1000手以上
* 流通盘20亿以上，撮合成交要在2000手以上

### 集合竞价看盘前的准备工作

一年之计在于春，一日之计在于晨。作为一个合格的投资者，在交易开始之前，往往必须要了解方方面面的财经信息，特别是会对市场产生重大影响的事件。比如国家产业政策，外围市场涨跌，大宗商品，国际局势，利率调整等做详细的了解和分析，以更好的预测和把握市场。就集合竞价之前，我们需要了解的信息如下：

* 浏览主要财经网站，了解主要市场信息。主要网站有东方财富网，中国财经信息网，上海证券报，中国证券报，慧博投研咨询等。

* 了解隔夜欧美主要市场的走势，欧洲主要看德指和英国富时，北美主要看道指，亚洲主要关注日韩走势。

* 了解隔夜大宗商品（有色、煤炭、农产品、原油、黄金等）信息，以上品种信息均可以通过文华财经软件或者东方财富看。

* 通过软件主图上的“信息地雷”了解重要标的股或持有股的行业信息、个股公告等。

### 集合竞价直击黑马（选股）

在集合竞价选取强势黑马个股时，要符合如下八大特点。

* 个股的60、120日中长期均线向上，中长期趋势走好，且5、10、20也开始多头排列，整体方向是向上的股票。最好处于上涨初期或者主升浪阶段，用缠论结构来看，日线最好处于上涨线段，周线处于买点延续。

* 跳空高开后，在前期的这一价格区间上没有或者少有结构压力位、筹码密集区，前高点的心理压力位等阻力因素的存在，同时也不要有中长期均线压制，最好有形态真空区或者筹码真空区。因为压力位附近的跳空高开很多是试盘，一旦抛压大会继续吸盘，没有压力的好处一是有拉升空间，二是抛压比较小，拉升相对轻松且持续。

* 个股集合竞价的成交金额要大，量比至少3倍以上，往往要达到10倍以上，有时高达30倍甚至100倍以上。虚拟成交量要大。

* 跳空高开之前，最好要经过放量上涨到缩量下跌再开始放量的过程，量是验证，是根本。

* 就跳空高开的次数来讲，最好是第一次跳空高开，以求安全性。

*就股性而言，之前要有大阳线或者涨停板出现，个股有涨停板基因。

* 当个股拉深一波有相对的涨幅后，在高位的高开要谨慎小心，存在在早盘高开，拉出价格空间，然后向下疯狂出货的嫌疑。

* 跳空高开幅度可以分为3种：高开2%以下为小幅高开，2%-5%为大幅高开，高开7%以上的为巨幅高开，高开幅度越大，则多方表现越强，上涨动能越大。但是如果当天高开太多的话当天介入利润空间已经太小，同时如果高开不多的话则多方实力值得商榷。所以正常情况下要选高开2%-5%的个股进行短线狙击。（当大盘以及板块处于牛市行情，并且个股形态相对强劲，则可以介入巨幅高开的个股，往往后面会有相对强势的上涨。）

* 补充，牛市和震荡市的高开可以做，下跌趋势的熊市中不可以做。

### 集合竞价实战选股（9点25分开始做）

在进行集合竞价直击涨停板的实战操作中，必须首先保证大盘处于多头行情中，至少是震荡市，熊市不建议操作。在此前提下，按照如下几个步骤进行选股。

* 按顺序依照涨跌幅、量比、涨速来观察。

* 着重观察高开2%以上的个股，特别是2%-7%的个股，一般在第一个页面选找即可。

* 

